<a href="https://colab.research.google.com/github/Temur0122/Pandas_topshiriq/blob/main/Murakkab_lvl999_muhim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar!

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirdik`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va pandas kutubxonasini chop eting.

In [4]:
import pandas as pd

**2.** Versiya va konfiguratsiyani tekshiring.

In [5]:

print(pd.__version__)
print(pd.__doc__)

1.5.3

pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

**3.** Pandas kutubxonasida mavjud bo'lgan barcha versiya ma'lumotlarini chop eting.

## `📌DataFrame: Asoslar`

DataFrames-da ma'lumotlarni tanlash(selecting), saralash(sorting), qo'shish(adding) va yig'ish(aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang:
``` python
import numpy as np
```

Quyidagi Python lug'ati(dictionary) `data` va Python ro'yxati(list) `labels` ni ko'rib chiqing:


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [6]:
import numpy as np
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

**4.** Ushbu `lug'at`(dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [7]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

 # (Dasturni davom ettiring!)
df = pd.DataFrame(data,index=labels)
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**5.** Ushbu DataFrame va uning ma'lumotlari haqidagi asosiy ma'lumotlarning qisqacha mazmunini ko'rsating.

`💡Ishora:` DataFrame-da chaqirilishi mumkin bo'lgan yagona usul mavjud.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes

**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [15]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** DataFrame `df`-dan faqat `animal` va `age` ustunlarini tanlang.

In [16]:
df[['animal','age']]

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi ma'lumotlarni tanlang.

In [23]:
df.iloc[[3, 4, 8]][['animal','age']]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Faqat `visits` soni 3 tadan ko'p bo'lgan qatorlarni tanlang.

In [24]:
df[df.visits > 3]
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

10. Yosh yo'qolgan qatorlarni tanlang, ya'ni `NaN`

In [8]:
df[df.age==None]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik bo'lgan umumiy qatorlarni tanlang.

In [9]:
df[(df.animal == 'cat') & (df.age<3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [10]:
df[(df.age>=2) & (df.age<=4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** `f` qatoridagi yoshni `1,5` ga o'zgartiring.

In [11]:
df.at['f','age']=1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** `df` yordamida `visits` qatorining yig'indisini hisoblang.

In [12]:
df14 = df.sum(axis=0)
df14['visits']

19

**15.** Har bir `animal` uchun o'rtacha yoshni `df` da hisoblang.

In [16]:
ortacha_yosh = df.groupby('animal')['age'].mean()
ortacha_yosh

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [18]:
df.animal.value_counts()

cat      4
dog      4
snake    2
Name: animal, dtype: int64

**17.** `animal` ustunida, `snake` so'zini `python` so'ziga o'zgartiring.

In [26]:
df['animal'] = df['animal'].replace('snake', 'python')

  animal  age  visits priority
c  snake  0.5       2       no
g  snake  4.5       1       no

## `📌DataFrame: Murakkab`

### Bir oz qiyinroq: to'g'ri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak bo'lishi mumkin

Oldingi bo'lim DataFrame-ning asosiy, ammo muhim operatsiyalari bo'yicha vazifalarni jamlagan edi. Quyida ma'lumotlarni kesishingiz kerak bo'lgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni o'z ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni o'z ichiga olgan ustun paydo bo'lishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [41]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
son=pd.DataFrame(df.A.unique())
son

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

**19.** Raqamli qiymatlardan iborat DataFrame berildi

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 o'lchovi
```

Qatordagi har bir elementdan satrning o'rtacha qiymatini qanday ayirish mumkin?

In [44]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
ortacha_s = df.mean(axis=1)
df.sub(ortacha_s,axis=0)

          0         1         2
0  0.147630  0.163456 -0.311086
1  0.000387  0.026683 -0.027070
2  0.534607 -0.231121 -0.303485
3 -0.103864 -0.044833  0.148698
4 -0.042843  0.029854  0.012989

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yig'indisi eng kichik ekanini hisoblang. U ustunning yorlig'ini qaytaring.

In [47]:
# DataFrame ni yaratish va ma'lumotlarni kiritish
import pandas as pd
import numpy as np

data = np.random.random(size=(5, 10))
columns = list('abcdefghij')
df = pd.DataFrame(data, columns=columns)

# Har bir ustunni yig'indisini hisoblash
column_sums = df.sum()

# Eng kichik yig'indini topish
min_sum = column_sums.min()

# Eng kichik yig'indi uchun ustunni aniqlash
min_sum_column = column_sums.idxmin()

# Eng kichik yig'indini va uning ustun yorlig'ini ekranga chiqarish
print("Eng kichik yig'indi:", min_sum)
print("Eng kichik yig'indi ustuni:", min_sum_column)

Eng kichik yig'indi: 1.3345151776460886
Eng kichik yig'indi ustuni: e

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrame ning har bir qatori uchun uchinchi `NaN` qiymatini o'z ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [50]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
target_columns = []
for idx, row in df.iterrows():
    count = 0
    for col, value in row.iteritems():
        if pd.isna(value):
            count += 1
            if count == 3:
                target_columns.append(col)
                break
target_columns
# Javobni bu yerga yozing!

<ipython-input-50-121b4c94e791>:15: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col, value in row.iteritems():

['e', 'c', 'd', 'h', 'd']

**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

In [53]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})


# Javobni bu yerga yozing!
result = df.groupby('grps')['vals'].nlargest(3).groupby('grps').sum()

print(result)

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**28.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega 'A' va 'B'. "A" dagi qiymatlar 1 dan 100 gacha (shu jumladan).

“A” dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yig'indisini hisoblang.

Javob quyidagicha bo'lishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [55]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# Javobni bu yerga yozing!
# A ustunidagi har bir 10 ta ketma-ket butun sonlar guruhi uchun B ustunidagi qiymatlar yig'indisini hisoblash
result = df.groupby(pd.cut(df['A'], bins=np.arange(0, 101, 10)))['B'].sum()

print(result)

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

**29.** 'X' butun son ustuni bo'lgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha bo'lishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [60]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
result = df['X'].diff().fillna(0)

# Natijani 'Y' ustuniga qo'shish
df['Y'] = result

   X    Y
0  7  0.0
1  2 -5.0
2  0 -2.0
3  3  3.0
4  4  1.0
5  2 -2.0
6  5  3.0
7  0 -5.0
8  3  3.0
9  4  1.0

##`📌Ma'lumotlarni tozalash`

Bu har doim sodir bo'ladi: kimdir sizga noto'g'ri tuzilgan satrlar, ro'yxatlar va yetishmayotgan ma'lumotlarni o'z ichiga olgan ma'lumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**30.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan so'ng u quyidagi ko'rinishga ega bo'lishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```

**31.** **FlightNumber** ustunidagi ba'zi qiymatlar yo'q. Ular `NaN` ko'rinishida yozilgan. Bu raqamlar har bir qatorda 10 ga ko'payishi kerak, shuning uchun 10055 va 10075 ni qo'yish kerak. Ushbu yetishmayotgan raqamlarni to'ldirish uchun `df` ni o'zgartiring va ustunni butun son ustuniga aylantiring.

**32.** **From\_To** ustunini ikkita alohida ustun ko'rinishida yozing.                                          

To'g'ri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

**34.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" bo'lishi kerak.)

**33**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ʻ'(British Airways. )'' `British Airways` ko'rinishida yozilishi kerak.

**34.** `df` dan **From_To** ustunini o'chiring va Temporary DataFrame `temp` ustunini qo'shing.

**34**. `RecentDelays` ustunida qiymatlar DataFrame-ga ro'yxat sifatida kiritilgan. Sizning vazifangiz birinchi qiymatni o'z ustunida, har bir ikkinchi qiymatni o'z ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat bo'lmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi ko'rinishda bo'lishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [87]:
import pandas as pd
import numpy as np
import re

# 30. DataFrame yaratish
data = {'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 'Budapest_PaRis', 'Brussels_londOn'],
        'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
        'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
        'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', '12. Air France', '"Swiss Air"']}

df = pd.DataFrame(data)

# 31. FlightNumber ustunidagi qiymatlarni to'ldirish
df['FlightNumber'].fillna(0, inplace=True)
df['FlightNumber'] = (df['FlightNumber'].astype(int) + 10).replace(0, np.nan)

# 32. From_To ustunini ikkita alohida ustun ko'rinishida yozish
temp_df = df['From_To'].str.split('_', expand=True)
temp_df.columns = ['From', 'To']

# 33. Airline ustunini tozalash va betartib yozish
df['Airline'] = df['Airline'].apply(lambda x: re.findall('[a-zA-Z\s]+', x)[0].strip())

# 34. df dan From_To ustunini o'chirib, Temporary DataFrame temp ustunini qo'shish
df.drop(columns='From_To', inplace=True)
df = pd.concat([temp_df, df], axis=1)

# 34. RecentDelays ustunidagi qiymatlarni DataFrame ga ko'chirish
delays = pd.DataFrame(df['RecentDelays'].tolist(), columns=['delay_1', 'delay_2', 'delay_3'])

# 34. Keraksiz ustunlarni o'chirib, qolgan ustunlarni nomlarni o'zgartirib asosiy DataFrame ga qo'shish
df.drop(columns='RecentDelays', inplace=True)
df = pd.concat([df, delays], axis=1)

# Natija
print(df)

       From         To  FlightNumber          Airline  delay_1  delay_2  \
0    LoNDon      paris         10055              KLM     23.0     47.0
1    MAdrid      miLAN            10       Air France      NaN      NaN
2    londON  StockhOlm         10075  British Airways     24.0     43.0
3  Budapest      PaRis            10       Air France     13.0      NaN
4  Brussels     londOn         10095        Swiss Air     67.0     32.0

   delay_3
0      NaN
1      NaN
2     87.0
3      NaN
4      NaN

##`📌Minesweeper`


### Minesweeper tarmog'ida xavfsiz kvadratlar uchun raqamlar yaratamiz!

💡 Agar siz Windowsning avvalgi versiyalaridan foydalangan bo'lsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz o'yin bilan tanish bo'lmasangiz, kvadratchalar to'plamini tasavvur qiling: bu kvadratlarning ba'zilari mineni yashiradi. Agar siz mineni bossangiz, darhol yo'qotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qo'shni bo'lgan kvadratchalarda qancha mine borligini ko'rsatadigan raqamni ko'rasiz. O'yinning maqsadi to'rdagi mine bo'lmagan barcha kvadratlarni ochishdir.

Ushbu bo'limda biz Minesweeper o'yini uchun kerakli ma'lumotlarni o'z ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qo'shni kvadratlarda topilgan minelar sonini aniqlaymiz!

**35**. Tasavvur qiling, biz Minesweeper o'yinini 5 dan 4 gacha bo'lgan panjarada o'ynayapmiz, ya'ni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani o'z ichiga olgan `'x'` va `'y'`. Ya'ni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

**36**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir bo'lish ehtimoli 0,4 bo'lishi kerak.

**37**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qo'shni kvadratlarda topilgan minelar soni bo'lishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv bo'lgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

**38**. Mineni o'z ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga o'zgartiring.

**39**. DataFrame-ni `adjacent` minelar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

##📌BONUS!

O'zingiz javob berishni istagan savolni kiriting va unga javob bering!

In [88]:
import pandas as pd
import numpy as np

# 35. Tasavvur qiling, 5 dan 4 gacha bo'lgan panjara
X = 5
Y = 4

# 36. DataFrame yaratish
df = pd.DataFrame([(x, y) for x in range(X) for y in range(Y)], columns=['x', 'y'])

# 37. Nol va birliklarni yaratish
df['safe'] = np.random.choice([0, 1], size=X*Y, p=[0.6, 0.4])

# 38. Adjacent ustunini yaratish va mineni hisoblash
adjacent = []
for _, row in df.iterrows():
    x, y = row['x'], row['y']
    adjacent_mines = df[(abs(df['x'] - x) <= 1) & (abs(df['y'] - y) <= 1) & (df != row).all(axis=1)]['safe'].sum()
    adjacent.append(adjacent_mines)

df['adjacent'] = adjacent

# 39. Adjacent ustunidagi NaNlarni o'zgartirish
df['adjacent'] = df['adjacent'].replace(0, np.nan)

# 40. DataFrame-ni adjacent minelar sonining panjarasiga aylantirish
minesweeper_board = df.pivot(index='y', columns='x', values='adjacent')

print(minesweeper_board)

x    0    1    2   3    4
y
0  1.0  NaN  2.0 NaN  1.0
1  NaN  NaN  2.0 NaN  1.0
2  1.0  1.0  3.0 NaN  NaN
3  NaN  NaN  1.0 NaN  1.0